### PR TITLE
Adds code of conduct

### PR DESCRIPTION
**Pull request by LarsFronius**
Since there will probably be a lot of opinionated discussion in this repo, more than elsewhere, where we usually focus on the code itself, I think this is of importance.

Taken from https://github.com/codeship-library/heroku-deployment/blob/master/CODE_OF_CONDUCT.md which took it from https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

### CODE REVIEW

**Comment by brettbuddin** [comment]
You think we are going to call each other bad names?

**Comment by LarsFronius** [comment]
I just think it's good practice. :)

**Review by markphelps — APPROVED** [review]
who defines trolling tho..

**Comment by markphelps** [comment]
Perhaps link to it in the README?

**Comment by brettbuddin** [comment]
👍

**Pull request merged**
